### ISSUE TITLE
Adding features

### ISSUE THREAD

**Issue by skandragon** [chalkers/wifiscanner#2]
I'm going to add more features to parse out more stuff I may care about, like the frequency (which is also channel), and other tidbits of information like signal strength.  This is to enable a wifi scanning project I am starting.

If I do this, would you like me to fork the code and submit pull requests?

**Comment by chalkers** [comment]
Sure!

**Comment by skandragon** [comment]
Awesome.  I'll close this, and open pull requests as I add bits.

**Comment by chalkers** [comment]
:+1:
